apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: nginx-dynsvc
  name: nginx-dynsvc
spec:
  output:
    to:
      kind: ImageStreamTag
      name: nginx-dynsvc:latest
  postCommit: {}
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/sterburg/kubernetes-nginx-servicediscovery.git
    secrets: []
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: debian:jessie
        namespace: nginx
    type: Docker
  triggers:
  - github:
      secret: wLZJoUS1RWe7Pc_-dtof
    type: GitHub
  - generic:
      secret: HU2kblUesnkwWvPFVTx4
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
